### ISSUE TITLE
Package warnings (utf8 and babel)

### ISSUE THREAD

**Issue by melissamonk-NOAA** [nwfsc-assess/sa4ss#7] opened 2020-12-10 15:36 UTC
This may or may not be an issue, but I'm receiving a few warnings when I compile a document via sa4ss.  
Package inputenc Warning: inputenc package ignored with utf8 based engines.
Package datetime2 Warning: Date-Time Language Module `english' not installed on 
input line 1913.
Package glossaries warning: NO language module detected for 'english'

I wanted to document these as I try out the package.  My laptop was re-formatted so I'm literally installing everything again as I go.

**Comment by chantelwetzel-noaa** [comment] 2020-12-10 15:41
I get the same set of warnings (but have been ignoring them) but it would be good to understand what is causing these errors and if it can be resolved.

**Comment by kellijohnson-NOAA** [comment] 2020-12-10 15:41
Thanks @melissamonk-NOAA the first one is my error that comes up on my machine as well, I know how to fix it but haven't yet. The second one is for 508 compliance where we define the language of the document. I am not sure which package this is, but I think it has to do with babel.
The third will hopefully go away with the installation of babel.

**Comment by melissamonk-NOAA** [comment] 2020-12-10 16:36
@kellijohnson-NOAA, the second two errors does appear to be a babel issue that's solved with \usepackage[english]{babel} . Note that I have not actually cloned the repo to pull requests.

**Comment by kellijohnson-NOAA** [comment] 2020-12-10 16:43
There is an [if statement in the style file](https://github.com/nwfsc-assess/sa4ss/blob/6b109e44a325772617d00cb333ba55001b615ef9/inst/rmarkdown/templates/sa/resources/sadraft.tex#L205) that is supposed to load babel when needed b/c a different package is used under some circumstances. I am not sure why this isn't working with tinytex, or maybe it isn't working for other reasons.

**Comment by kellijohnson-NOAA** [comment] 2020-12-10 16:44
hmm, now that I think about it more, maybe babel needs to be loaded before this and the statement just alters the specifications. Clearly, I need to think about this more.

**Comment by melissamonk-NOAA** [comment] 2020-12-10 17:00
Thanks for that link...I was looking in [the sa4ss.sty style file](https://github.com/nwfsc-assess/sa4ss/blob/master/inst/rmarkdown/templates/sa/skeleton/sa4ss.sty) .  Obviously still learning my way around what you've done!

**Comment by kellijohnson-NOAA** [comment] 2020-12-16 23:17
@melissamonk-NOAA or @chantelwetzel-noaa can you run the following from the command line on the computer that was generating the above errors
```
tlmgr search --global --file "/datetime2.sty"
```
where the above was recommended on the [tinytex website](yihui.org/tinytex)
I think that you are just missing a package that is used for dates, but I don't want to call the package directly because it is just being used as a dependent of something else I think. I don't have the problem on my machine because I use MiKTeX.

**Comment by chantelwetzel-noaa** [comment] 2020-12-16 23:42
I ran the above command on the command line, although I don't have the tech skills to know if I did it right or if it worked.  Either way I am still getting both of the above errors identified in this issue.  I wanted to read up to see if I misunderstood the directions but the the link provided does not work.

**Comment by kellijohnson-NOAA** [comment] 2020-12-17 00:07
The command doesn't do anything other than let us know where the file exists on your computer. I am trying to see if the package is installed or if it needs to be installed. I updated the link.

**Comment by chantelwetzel-noaa** [comment] 2020-12-17 00:15
Ok.  This is what I get when I run this on the command line:

tlmgr.pl: package repository https://ctan.math.illinois.edu/systems/texlive/tlnet (verified)
datetime2:
        texmf-dist/tex/latex/datetime2/datetime2.sty

I still don't know what is happening  :)  I will read through the tinytex guide and see if I can understand what I should be doing and / or seeing.  Thanks for digging in on this @kellijohnson-NOAA

**Comment by kellijohnson-NOAA** [comment] 2020-12-17 00:18
thanks for the output, it is saying that the datetime2.sty file is in the datetime2 package; so, no smoking gun there. now, can you add \usepackage{datetime2} to the sa4ss.sty file in your local folder and run bookdown::render_book() to see if the error goes away. we might just have to call it directly.

**Comment by kellijohnson-NOAA** [comment] 2020-12-17 15:49
[tinytex](https://github.com/yihui/tinytex) lists the [LaTeX packages that are installed automatically](https://tinytex.yihui.org/pkgs-yihui.txt) and datetime2 is not standard. There is a tinytex function called tinytex::post_install_config(extra_packages) that we might be able to call if adding datetime2 or datetime2-english to the .sty file doesn't work.

**Comment by chantelwetzel-noaa** [comment] 2020-12-17 16:06
Adding \usepackage{datetime2} the sty file did not work and actually resulted in an error when rendering:

Unmatched ( in regex; marked by <-- HERE in m//( <-- HERE .sty/ at C:\Users\CHANTE~1.WET\AppData\Roaming\TinyTeX\texmf-dist\scripts\texlive\tlmgr.pl line 1782.
Error in grep(paste0("/", x[j], "$"), l) : 
  invalid regular expression '/(.sty$', reason 'Missing ')''

The post_intall_config function is not included in my version of the tinytex package and I am unable to find information on it online. Can you provide the information that found on this function?

**Comment by kellijohnson-NOAA** [comment] 2020-12-17 16:16
https://github.com/yihui/tinytex/blob/e75e44b1b2b2653182b396f1796802a8b2090dd8/R/install.R#L372 it is not exported, which makes me think that I am thinking to hard about this and that there is a different way to go about this :( Maybe we should instead be using tinytex::tlmgr_install() but it says LaTeX packages should be installed on the fly. Can you try
```
tinytex::tlmgr_install("datetime2")
```

**Comment by chantelwetzel-noaa** [comment] 2020-12-17 16:34
This function appeared to work, but I am not sure if it executed anything since I already had the datetime2 package on my machine.  Running the above line resulted in the following output on the R terminal:

tlmgr install datetime2
tlmgr.pl: package repository https://ctan.math.illinois.edu/systems/texlive/tlnet (verified)
tlmgr.pl install: package already present: datetime2

I then tried to render the document but got the same warning about datetime2: 

Package datetime2 Warning: Date-Time Language Module `english' not installed on 
input line 1913.

I then tried retaining the \usepackage{datetime2} in the sty file but got the same error as I did above when rendering.  Given that the current package works but just throws a warning, I am not terribly concerned about fixing this right away, however, long-term we will want to sort it out.

**Comment by kellijohnson-NOAA** [comment] 2020-12-17 16:58
Can you look at 2 things before we table it for a while?
(1) try tinytex::tlmgr_install("datetime2-english")
(2) i am wondering what line 1913 is? Is there a line 1913 in _main.tex? It would just be nice to know why in the heck we have to have the datetime2 package anyway, I think it is because of babel, but I am not certain. Typically, it is needed for things like `\today` which we don't have I think.

**Comment by chantelwetzel-noaa** [comment] 2020-12-17 19:55
Eureka!  Specifying that we should install the datetime2-english package eliminated this warning.  I forgot to mention that there is no line 1913 in the _main.tex file (less than 1000 lines in the file total) which made the error even more puzzling.

**Comment by chantelwetzel-noaa** [comment] 2021-01-04 00:10
I just tried to create a new document based on the current version of the package and the datetime2-english package being required on line 63 of the sa4ss.sty file results in a render issue.  Commenting out this line allows the document to render, however, I received an error about english not being found in the glossaries. I installed the "glossaries-english" package using the command tinytex::tlmgr_install("glossaries-english"). I then added this package to the sa4ss.sty file but then received an error when compiling due to the package being missing.  I commented out this new package (I now have both the datetime2-english and glossaries-english commented out but installed via tinytex) and now was able to render the document without recieving any errors or warnings.  I don't know why this occured but we may want to look back into this issue. I am confused why requiring these packages in the sa4ss.sty document, which are installed, are preventing the document to render.

**Comment by kellijohnson-NOAA** [comment] 2021-01-04 15:35
I wonder if how they are being called is why they are not working with tinytex. I am using MikTex, so I don't run into the same problem. I will try to install tinytex on another machine and see if I get the same error.

**Comment by iantaylor-NOAA** [comment] 2021-01-09 00:03
Adding to this discussion in case it helps. 

I just tried to compile to SS_documentation repository to confirm that I'm not breaking anything while adding a few things. Clicking "Compile PDF" in RStudio as I'd done before led to errors about missing .sty files.
I was able to install these one at a time using `tinytex::parse_install("SS330_User_Manual.log")` (inspired by Info at https://bookdown.org/yihui/rmarkdown-cookbook/install-latex-pkgs.html) but the next compile just led to an error about a different .sty file missing.

I finally discovered that running `tinytex::pdflatex('SS330_User_Manual.tex')` in R to compile instead of using RStudio automatically installed the missing packages (including `babel-english`, but not those identified as problematic in this issue (I haven't tried compiling an sa4ss file).

**Comment by chantelwetzel-noaa** [comment] 2021-01-09 00:09
@iantaylor-NOAA Keep in mind that I enforce the policy of "if you break it - you bought it" with the S330_User_Manual.  Since you were able to get this to work on the SS user manual, I will be interested to hear what you encounter when using sa4ss.

**Comment by iantaylor-NOAA** [comment] 2021-01-12 01:22
I just tried `bookdown::render_book("00a.Rmd", clean = FALSE, output_dir = getwd())`
and it loaded some things automatically, but not `datetime2-english.sty` (see output below).

Also, I had these messages following the example in README: `argument "authors" is missing, with no default` and `Error in setwd("doc") : cannot change working directory`. I'm assuming the example is just out of date with the current code.

```
tlmgr.pl: package repository https://mirrors.concertpass.com/tex-archive/systems/texlive/tlnet (not verified: gpg unavailable)
[1/1, ??:??/??:??] install: hanging [2k]
running mktexlsr ...
done running mktexlsr.
tlmgr.pl: package log updated: C:/Users/ian.taylor/AppData/Roaming/TinyTeX/texmf-var/web2c/tlmgr.log

tlmgr.pl: package repository https://mirrors.concertpass.com/tex-archive/systems/texlive/tlnet (not verified: gpg unavailable)
[1/2, ??:??/??:??] install: hyperxmp.win32 [1k]
[2/2, 00:00/00:00] install: hyperxmp [15k]
running mktexlsr ...
done running mktexlsr.
tlmgr.pl: package log updated: C:/Users/ian.taylor/AppData/Roaming/TinyTeX/texmf-var/web2c/tlmgr.log
tlmgr.pl: package repository https://mirrors.concertpass.com/tex-archive/systems/texlive/tlnet (not verified: gpg unavailable)
[1/1, ??:??/??:??] install: ifmtarg [1k]
running mktexlsr ...
done running mktexlsr.
tlmgr.pl: package log updated: C:/Users/ian.taylor/AppData/Roaming/TinyTeX/texmf-var/web2c/tlmgr.log
tlmgr.pl: package repository https://mirrors.concertpass.com/tex-archive/systems/texlive/tlnet (not verified: gpg unavailable)
[1/1, ??:??/??:??] install: luacode [3k]
running mktexlsr ...
done running mktexlsr.
tlmgr.pl: package log updated: C:/Users/ian.taylor/AppData/Roaming/TinyTeX/texmf-var/web2c/tlmgr.log
tlmgr.pl: package repository https://mirrors.concertpass.com/tex-archive/systems/texlive/tlnet (not verified: gpg unavailable)
[1/2, ??:??/??:??] install: ctablestack [2k]
[2/2, 00:00/00:00] install: luatexbase [4k]
running mktexlsr ...
done running mktexlsr.
tlmgr.pl: package log updated: C:/Users/ian.taylor/AppData/Roaming/TinyTeX/texmf-var/web2c/tlmgr.log
! LaTeX Error: File `datetime2-english.sty' not found.

! Emergency stop.
```

**Comment by chantelwetzel-noaa** [comment] 2021-01-12 13:26
Thank you for the feedback @iantaylor-NOAA.  Try running this line in your R seession:

tinytex::tlmgr_install("datetime2-english") 

I think the other two warning messages were because the example in readme does not include the directions to set your working directory to where you want the document created and the that draft function does not include specifying the title or authors.  Can you do the above install and follow the directions [here](https://github.com/chantelwetzel-noaa/copper_rockfish_2021/blob/master/write_up/sa4ss_guide/Using_sa4ss.pdf) which are my own personal notes and let us know how that works?

**Comment by chantelwetzel-noaa** [comment] 2021-01-12 18:20
I think you are now encountering the most recent error that I ran into.  I had to comment out (%) the \usepackage{datetime2-english} line in the sa4ss.sty file to render a document which is effectively the solution that you are proposing.  I have been able to render documents without this package that look fine but I am not entirely sure why this package was added and my "solution" may create issues that I am unaware of.

**Comment by kellijohnson-NOAA** [comment] 2021-01-18 18:37
I am working on this now and I think I found part of the answer [here](https://tex.stackexchange.com/questions/457376/datetime2-scientific-english-format) on stackexchange. The problem was, I didn't understand the structure of Latex packages, where the english module is part of the datetime2 package and you have to specify which module you want in square brackets rather than using the name-module. My mistake. Should be fixed with 

You should see the following in the output printed to the screen:
```
tlmgr.pl: package log updated: C:/Users/kelli/AppData/Roaming/TinyTeX/texmf-var/web2c/tlmgr.log
tlmgr.pl: package repository http://ctan.mirrors.hoobly.com/systems/texlive/tlnet (verified)
[1/1, ??:??/??:??] install: babel-english [3k]
```

Though, now I am seeing the following:
```
Package datetime2 Warning: Date-Time Language Module `english' not installed on 
input line 1913.
Package glossaries Warning: No language module detected for `english'.
(glossaries)                Language modules need to be installed separately.
(glossaries)                Please check on CTAN for a bundle called
(glossaries)                `glossaries-english' or similar.
```
Removed with
```
tlmgr_install("datetime2-english")
tlmgr_install("glossaries-english")
```

**Comment by kellijohnson-NOAA** [comment] 2021-03-02 22:35
- [ ] Need to create helper functions that ensure these packages are loaded ahead of time behind the scenes.

**Comment by kellijohnson-NOAA** [comment] 2021-05-25 17:34
Thanks to @yihui for fixing this in [tinytex #311](https://github.com/yihui/tinytex/issues/311)!

**Closed** 2021-05-25 17:35 UTC
Labels: type: error message, type: installation

**Comment by yihui** [comment] 2021-05-25 17:50
You are welcome!

**Comment by brry** [comment] 2021-08-10 01:17
For reference: I have `\usepackage[showzone=false,showseconds=false]{datetime2}` and `\DTMnow` in my Rnw document.  
When compiling with tinytex Version **0.32**, I also got _Package datetime2 Warning: Date-Time Language Module 'english' not installed on input line 1913._
I simply ran `tinytex::tlmgr_install("datetime2-english")` and recompiled without any changes to the document and all is good.
I thought **0.32** should already have the automatic fix, hence my comment. I am happy now, so no reaction needed.

**Comment by yihui** [comment] 2021-08-10 02:02
0.32 should fix this problem automatically. If not, it'll be great to provide a minimal reproducible example so I can take another look.

**Comment by kellijohnson-NOAA** [comment] 2021-08-10 14:29
I **think** the reason that tinytex did not automatically install datetime2-english in the example given by @brry 
```
\usepackage[showzone=false,showseconds=false]{datetime2}
```
is because the language is not declared inside the square brackets. Whereas, in [sa4ss the language is declared](https://github.com/nwfsc-assess/sa4ss/blob/10f4377bde5f6e3357c8f53b4f3c295501b8c0db/inst/rmarkdown/templates/sa/skeleton/sa4ss.sty#L55).

**Comment by brry** [comment] 2021-08-11 16:35
I ran
```r
tinytex::tlmgr_remove("datetime2-english")
```
and in `test_dt.Rnw` have the following content:

```tex
\documentclass{beamer}
\usepackage[showzone=false,showseconds=false]{datetime2}
\begin{document}
\begin{frame}{Stuff}
pdf created:  \DTMnow 
\end{frame}
\end{document}
```

click Compile and then search in the log for   datetime2 Warning   
After running `tinytex::tlmgr_install("datetime2-english")` it compiles without the warning. In both cases, the PDF looks fine.

**Comment by yihui** [comment] 2021-08-11 18:20
I can't reproduce the problem; datetime2-english can be automatically installed on my computer after I remove it and compile the Rnw example you provided.

If you are using RStudio, be sure to check the option "Use tinytex when compiling .tex":

![image](https://user-images.githubusercontent.com/163582/129082102-c0a9fe71-b31c-43de-b869-f0308a2d616b.png)

Otherwise tinytex won't be used, so missing LaTeX packages won't be automatically installed.

**Comment by brry** [comment] 2021-08-12 15:44
I had not set Rstudio to always compile with tinytex, but even with all the settings as per your screenshot, no automated installation happens.
After I turned off "Always enable Rnw concordance", I now see the warning message in Rstudios Compile PDF window - with additional information:
_Warning: **tracklang.sty**:1913: Date-Time Language Module `english' not installed on input line 1913._

As said, I'm happy fixing this manually.
